version: 2

project_name: closedsspm

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: closedsspm
    main: ./cmd/closedsspm
    binary: closedsspm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: closedsspm-mcp
    main: ./cmd/mcp
    binary: closedsspm-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - policies/**/*

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

nfpms:
  - id: deb
    package_name: closedsspm
    vendor: PiotrMackowski
    homepage: https://github.com/PiotrMackowski/ClosedSSPM
    maintainer: Piotr Mackowski <115957655+PiotrMackowski@users.noreply.github.com>
    description: Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations.
    license: Apache-2.0
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/closedsspm/LICENSE
      - src: README.md
        dst: /usr/share/doc/closedsspm/README.md

  - id: rpm
    package_name: closedsspm
    vendor: PiotrMackowski
    homepage: https://github.com/PiotrMackowski/ClosedSSPM
    maintainer: Piotr Mackowski <115957655+PiotrMackowski@users.noreply.github.com>
    description: Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations.
    license: Apache-2.0
    formats:
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/closedsspm/LICENSE
      - src: README.md
        dst: /usr/share/doc/closedsspm/README.md

dockers:
  - id: closedsspm-amd64
    ids:
      - closedsspm
      - closedsspm-mcp
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/piotrmackowski/closedsspm:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ClosedSSPM"
      - "--label=org.opencontainers.image.description=Open Source SaaS Security Posture Management"
      - "--label=org.opencontainers.image.url=https://github.com/PiotrMackowski/ClosedSSPM"
      - "--label=org.opencontainers.image.source=https://github.com/PiotrMackowski/ClosedSSPM"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--platform=linux/amd64"

  - id: closedsspm-arm64
    ids:
      - closedsspm
      - closedsspm-mcp
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/piotrmackowski/closedsspm:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=ClosedSSPM"
      - "--label=org.opencontainers.image.description=Open Source SaaS Security Posture Management"
      - "--label=org.opencontainers.image.url=https://github.com/PiotrMackowski/ClosedSSPM"
      - "--label=org.opencontainers.image.source=https://github.com/PiotrMackowski/ClosedSSPM"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/piotrmackowski/closedsspm:{{ .Version }}"
    image_templates:
      - "ghcr.io/piotrmackowski/closedsspm:{{ .Version }}-amd64"
      - "ghcr.io/piotrmackowski/closedsspm:{{ .Version }}-arm64"
  - name_template: "ghcr.io/piotrmackowski/closedsspm:latest"
    image_templates:
      - "ghcr.io/piotrmackowski/closedsspm:{{ .Version }}-amd64"
      - "ghcr.io/piotrmackowski/closedsspm:{{ .Version }}-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
