version: 2

project_name: closedsspm

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: closedsspm
    main: ./cmd/closedsspm
    binary: closedsspm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: closedsspm-mcp
    main: ./cmd/mcp
    binary: closedsspm-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - policies/**/*

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    artifacts: checksum
    output: true
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

nfpms:
  - id: deb
    package_name: closedsspm
    vendor: PiotrMackowski
    homepage: https://github.com/PiotrMackowski/ClosedSSPM
    maintainer: Piotr Mackowski <115957655+PiotrMackowski@users.noreply.github.com>
    description: Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations.
    license: Apache-2.0
    formats:
      - deb
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/closedsspm/LICENSE
      - src: README.md
        dst: /usr/share/doc/closedsspm/README.md

  - id: rpm
    package_name: closedsspm
    vendor: PiotrMackowski
    homepage: https://github.com/PiotrMackowski/ClosedSSPM
    maintainer: Piotr Mackowski <115957655+PiotrMackowski@users.noreply.github.com>
    description: Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations.
    license: Apache-2.0
    formats:
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/closedsspm/LICENSE
      - src: README.md
        dst: /usr/share/doc/closedsspm/README.md

dockers_v2:
  - ids:
      - closedsspm
      - closedsspm-mcp
    images:
      - "ghcr.io/piotrmackowski/closedsspm"
    tags:
      - "{{ .Version }}"
      - latest
    labels:
      "org.opencontainers.image.title": "ClosedSSPM"
      "org.opencontainers.image.description": "Open Source SaaS Security Posture Management"
      "org.opencontainers.image.url": "https://github.com/PiotrMackowski/ClosedSSPM"
      "org.opencontainers.image.source": "https://github.com/PiotrMackowski/ClosedSSPM"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "Apache-2.0"
    platforms:
      - linux/amd64
      - linux/arm64

homebrew_casks:
  - name: closedsspm
    binaries:
      - closedsspm
      - closedsspm-mcp
    repository:
      owner: PiotrMackowski
      name: homebrew-closedsspm
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/PiotrMackowski/ClosedSSPM
    description: Open Source SaaS Security Posture Management — audit SaaS platforms for security misconfigurations.
    license: Apache-2.0
    commit_author:
      name: Piotr Mackowski
      email: 115957655+PiotrMackowski@users.noreply.github.com
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm"]
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/closedsspm-mcp"]
          end

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
